import { library } from "@fortawesome/fontawesome-svg-core";

import {
  faArrowUpRightFromSquare,
  faCheck,
  faCircle,
  faComments as falComments,
  faCheckCircle,
  faCircleQuestion,
  faCircleExclamation,
  faChevronsRight,
  faInfo,
  faCloudSun,
  faInfoCircle,
  faExclamationTriangle,
  faExclamationCircle,
  faArrowUp,
  faArrowsRotate,
  faAngleRight,
  faAngleLeft,
  faAngleDown,
  faBolt,
  faEye,
  faFileExcel,
  faEllipsisVertical,
  faEyeSlash,
  faFunction,
  faCaretDown,
  faCaretUp,
  faFilter,
  faPenCircle,
  faSpinner,
  faNotEqual,
  faGears,
  faTable,
  faOption,
  faTimes,
  faTimesCircle,
  faTrashAlt,
  faPlus,
  faUpload,
  faBars,
  faTransformerBolt,
  faCodePullRequest,
  faXmarkCircle,
  faWrench as falWrench
} from "@fortawesome/pro-light-svg-icons";

import {
  faBadgeCheck,
  faLock,
  faWrench as fasWrench,
  faComments as fasComments
} from "@fortawesome/pro-solid-svg-icons";

import { FontAwesomeIcon, FontAwesomeLayers, FontAwesomeLayersText } from "@fortawesome/vue-fontawesome";

// @ts-ignore
library.add(
  faArrowUpRightFromSquare,
  faCircle,
  faCloudSun,
  faArrowsRotate,
  faCheck,
  faCheckCircle,
  faChevronsRight,
  faCircleQuestion,
  faCircleExclamation,
  falComments,
  fasComments,
  faFileExcel,
  faGears,
  faFunction,
  faInfo,
  faNotEqual,
  faInfoCircle,
  faExclamationTriangle,
  faExclamationCircle,
  faArrowUp,
  faAngleRight,
  faAngleLeft,
  faAngleDown,
  faBolt,
  faPenCircle,
  faLock,
  faCodePullRequest,
  faOption,
  faEye,
  faEllipsisVertical,
  faEyeSlash,
  faFilter,
  faCaretDown,
  faCaretUp,
  faSpinner,
  faPlus,
  faTable,
  faTimes,
  faTimesCircle,
  faTrashAlt,
  faUpload,
  faBars,
  faTransformerBolt,
  faXmarkCircle,
  faBadgeCheck,
  falWrench,
  fasWrench
);

export { FontAwesomeIcon, FontAwesomeLayers, FontAwesomeLayersText };
